name: isarx
description: A sample command-line application.
version: 0.0.0
homepage: https://youtube.com/@azkadev
repository: https://github.com/azkadev/isarx.git
environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  isar_generator: ^3.0.5
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  isar: ^3.0.5
